#define MASTER_RIGHT

#define FORCE_NXRO

#define OS_DETECTION_DEBOUNCE 250
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U

#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_DEFAULT_ON true
    #define RGB_MATRIX_SPLIT {29, 29}
    #define DRIVER_LED_TOTAL 58
    #define RGB_MATRIX_LED_COUNT 58

    #define RGB_DISABLE_WHEN_USB_SUSPENDED // turn off effects when suspended
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS

    #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 128 // limits maximum brightness of LEDs to 150 out of 255. Higher may cause the controller to crash.
    #define RGB_MATRIX_HUE_STEP 8
    #define RGB_MATRIX_SAT_STEP 8
    #define RGB_MATRIX_VAL_STEP 8
    #define RGB_MATRIX_SPD_STEP 10

    #define ENABLE_RGB_MATRIX_BREATHING
    #define ENABLE_RGB_MATRIX_DIGITAL_RAIN
    #define ENABLE_RGB_MATRIX_HUE_BREATHING
    #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
    #define ENABLE_RGB_MATRIX_RAINDROPS
    #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
    #define ENABLE_RGB_MATRIX_SPLASH
    #define ENABLE_RGB_MATRIX_TYPING_HEATMAP

    #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_RAINDROPS

#endif
