SPLIT_KEYBOARD = yes
OLED_ENABLE = yes

BOARD = GENERIC_RP_RP2040


ENCODER_MAP_ENABLE = yes

# short press lower case long press upper case
AUTO_SHIFT_ENABLE = yes
LEADER_ENABLE = yes

CONSOLE_ENABLE = yes

LTO_ENABLED = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
CAPS_WORD_ENABLE = yes
BOOTMAGIC_ENABLE = yes
OS_DETECTION_ENABLE = yes

# Enable custom RGB matrix configuration
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812
ifeq ($(RGB_MATRIX_ENABLE),yes)
	SRC += ./rgb.c
endif

RGB_MATRIX_NONE = yes
RGB_MATRIX_BREATHING = yes
RGB_MATRIX_DIGITAL_RAIN = yes
RGB_MATRIX_HUE_BREATHING = yes
RGB_MATRIX_SOLID_MULTISPLASH = yes
RGB_MATRIX_SOLID_REACTIVE = yes
RGB_MATRIX_RAINDROPS = yes
RGB_MATRIX_TYPING_HEATMAP = yes
RGB_MATRIX_SPLASH = yes
